// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: tada/gateway/admin/change_tariff_service.proto

/*
Package admin is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package admin

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"gitlab.tada.team/tdapis/go-genproto/tada/api/billing"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_ChangeTariff_GetChangesTariffsByPersonalAccount_0(ctx context.Context, marshaler runtime.Marshaler, client ChangeTariffClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq billing.GetChangesTariffsByPersonalAccountRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetChangesTariffsByPersonalAccount(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_ChangeTariff_GetChangesTariffsByPersonalAccount_0(ctx context.Context, marshaler runtime.Marshaler, server ChangeTariffServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq billing.GetChangesTariffsByPersonalAccountRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetChangesTariffsByPersonalAccount(ctx, &protoReq)
	return msg, metadata, err

}

func request_ChangeTariff_CreateChangeTariffOnPersonalAccount_0(ctx context.Context, marshaler runtime.Marshaler, client ChangeTariffClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq billing.CreateChangeTariffOnPersonalAccountRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateChangeTariffOnPersonalAccount(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_ChangeTariff_CreateChangeTariffOnPersonalAccount_0(ctx context.Context, marshaler runtime.Marshaler, server ChangeTariffServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq billing.CreateChangeTariffOnPersonalAccountRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateChangeTariffOnPersonalAccount(ctx, &protoReq)
	return msg, metadata, err

}

func request_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0(ctx context.Context, marshaler runtime.Marshaler, client ChangeTariffClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq billing.DeleteChangeTariffOnPersonalAccountRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.DeleteChangeTariffOnPersonalAccount(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0(ctx context.Context, marshaler runtime.Marshaler, server ChangeTariffServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq billing.DeleteChangeTariffOnPersonalAccountRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.DeleteChangeTariffOnPersonalAccount(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterChangeTariffHandlerServer registers the http handlers for service ChangeTariff to "mux".
// UnaryRPC     :call ChangeTariffServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterChangeTariffHandlerFromEndpoint instead.
func RegisterChangeTariffHandlerServer(ctx context.Context, mux *runtime.ServeMux, server ChangeTariffServer) error {

	mux.Handle("POST", pattern_ChangeTariff_GetChangesTariffsByPersonalAccount_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/tada.gateway.admin.ChangeTariff/GetChangesTariffsByPersonalAccount", runtime.WithHTTPPathPattern("/gateway/v1/admin.ChangeTariff/GetChangesTariffsByPersonalAccount"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_ChangeTariff_GetChangesTariffsByPersonalAccount_0(ctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ChangeTariff_GetChangesTariffsByPersonalAccount_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PUT", pattern_ChangeTariff_CreateChangeTariffOnPersonalAccount_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/tada.gateway.admin.ChangeTariff/CreateChangeTariffOnPersonalAccount", runtime.WithHTTPPathPattern("/gateway/v1/admin.ChangeTariff/CreateChangeTariffOnPersonalAccount"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_ChangeTariff_CreateChangeTariffOnPersonalAccount_0(ctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ChangeTariff_CreateChangeTariffOnPersonalAccount_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/tada.gateway.admin.ChangeTariff/DeleteChangeTariffOnPersonalAccount", runtime.WithHTTPPathPattern("/gateway/v1/admin.ChangeTariff/DeleteChangeTariffOnPersonalAccount"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0(ctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterChangeTariffHandlerFromEndpoint is same as RegisterChangeTariffHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterChangeTariffHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterChangeTariffHandler(ctx, mux, conn)
}

// RegisterChangeTariffHandler registers the http handlers for service ChangeTariff to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterChangeTariffHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterChangeTariffHandlerClient(ctx, mux, NewChangeTariffClient(conn))
}

// RegisterChangeTariffHandlerClient registers the http handlers for service ChangeTariff
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "ChangeTariffClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "ChangeTariffClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "ChangeTariffClient" to call the correct interceptors.
func RegisterChangeTariffHandlerClient(ctx context.Context, mux *runtime.ServeMux, client ChangeTariffClient) error {

	mux.Handle("POST", pattern_ChangeTariff_GetChangesTariffsByPersonalAccount_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateContext(ctx, mux, req, "/tada.gateway.admin.ChangeTariff/GetChangesTariffsByPersonalAccount", runtime.WithHTTPPathPattern("/gateway/v1/admin.ChangeTariff/GetChangesTariffsByPersonalAccount"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_ChangeTariff_GetChangesTariffsByPersonalAccount_0(ctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ChangeTariff_GetChangesTariffsByPersonalAccount_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PUT", pattern_ChangeTariff_CreateChangeTariffOnPersonalAccount_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateContext(ctx, mux, req, "/tada.gateway.admin.ChangeTariff/CreateChangeTariffOnPersonalAccount", runtime.WithHTTPPathPattern("/gateway/v1/admin.ChangeTariff/CreateChangeTariffOnPersonalAccount"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_ChangeTariff_CreateChangeTariffOnPersonalAccount_0(ctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ChangeTariff_CreateChangeTariffOnPersonalAccount_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateContext(ctx, mux, req, "/tada.gateway.admin.ChangeTariff/DeleteChangeTariffOnPersonalAccount", runtime.WithHTTPPathPattern("/gateway/v1/admin.ChangeTariff/DeleteChangeTariffOnPersonalAccount"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0(ctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_ChangeTariff_GetChangesTariffsByPersonalAccount_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"gateway", "v1", "admin.ChangeTariff", "GetChangesTariffsByPersonalAccount"}, ""))

	pattern_ChangeTariff_CreateChangeTariffOnPersonalAccount_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"gateway", "v1", "admin.ChangeTariff", "CreateChangeTariffOnPersonalAccount"}, ""))

	pattern_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"gateway", "v1", "admin.ChangeTariff", "DeleteChangeTariffOnPersonalAccount"}, ""))
)

var (
	forward_ChangeTariff_GetChangesTariffsByPersonalAccount_0 = runtime.ForwardResponseMessage

	forward_ChangeTariff_CreateChangeTariffOnPersonalAccount_0 = runtime.ForwardResponseMessage

	forward_ChangeTariff_DeleteChangeTariffOnPersonalAccount_0 = runtime.ForwardResponseMessage
)
