// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package billing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TeamClient is the client API for Team service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeamClient interface {
	AddTeamOnPersonalAccount(ctx context.Context, in *AddTeamOnPersonalAccountRequest, opts ...grpc.CallOption) (*AddTeamOnPersonalAccountResponse, error)
	DeleteTeamFromPersonalAccount(ctx context.Context, in *DeleteTeamFromPersonalAccountRequest, opts ...grpc.CallOption) (*DeleteTeamFromPersonalAccountResponse, error)
	GetTeamsOnPersonalAccount(ctx context.Context, in *GetTeamsOnPersonalAccountRequest, opts ...grpc.CallOption) (*GetTeamsOnPersonalAccountResponse, error)
	CheckTeamOnPersonalAccount(ctx context.Context, in *CheckTeamOnPersonalAccountRequest, opts ...grpc.CallOption) (*CheckTeamOnPersonalAccountResponse, error)
	GetTeamBitrate(ctx context.Context, in *GetTeamBitrateRequest, opts ...grpc.CallOption) (*GetTeamBitrateResponse, error)
}

type teamClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamClient(cc grpc.ClientConnInterface) TeamClient {
	return &teamClient{cc}
}

func (c *teamClient) AddTeamOnPersonalAccount(ctx context.Context, in *AddTeamOnPersonalAccountRequest, opts ...grpc.CallOption) (*AddTeamOnPersonalAccountResponse, error) {
	out := new(AddTeamOnPersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Team/AddTeamOnPersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamClient) DeleteTeamFromPersonalAccount(ctx context.Context, in *DeleteTeamFromPersonalAccountRequest, opts ...grpc.CallOption) (*DeleteTeamFromPersonalAccountResponse, error) {
	out := new(DeleteTeamFromPersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Team/DeleteTeamFromPersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamClient) GetTeamsOnPersonalAccount(ctx context.Context, in *GetTeamsOnPersonalAccountRequest, opts ...grpc.CallOption) (*GetTeamsOnPersonalAccountResponse, error) {
	out := new(GetTeamsOnPersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Team/GetTeamsOnPersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamClient) CheckTeamOnPersonalAccount(ctx context.Context, in *CheckTeamOnPersonalAccountRequest, opts ...grpc.CallOption) (*CheckTeamOnPersonalAccountResponse, error) {
	out := new(CheckTeamOnPersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Team/CheckTeamOnPersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamClient) GetTeamBitrate(ctx context.Context, in *GetTeamBitrateRequest, opts ...grpc.CallOption) (*GetTeamBitrateResponse, error) {
	out := new(GetTeamBitrateResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Team/GetTeamBitrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamServer is the server API for Team service.
// All implementations must embed UnimplementedTeamServer
// for forward compatibility
type TeamServer interface {
	AddTeamOnPersonalAccount(context.Context, *AddTeamOnPersonalAccountRequest) (*AddTeamOnPersonalAccountResponse, error)
	DeleteTeamFromPersonalAccount(context.Context, *DeleteTeamFromPersonalAccountRequest) (*DeleteTeamFromPersonalAccountResponse, error)
	GetTeamsOnPersonalAccount(context.Context, *GetTeamsOnPersonalAccountRequest) (*GetTeamsOnPersonalAccountResponse, error)
	CheckTeamOnPersonalAccount(context.Context, *CheckTeamOnPersonalAccountRequest) (*CheckTeamOnPersonalAccountResponse, error)
	GetTeamBitrate(context.Context, *GetTeamBitrateRequest) (*GetTeamBitrateResponse, error)
	mustEmbedUnimplementedTeamServer()
}

// UnimplementedTeamServer must be embedded to have forward compatible implementations.
type UnimplementedTeamServer struct {
}

func (UnimplementedTeamServer) AddTeamOnPersonalAccount(context.Context, *AddTeamOnPersonalAccountRequest) (*AddTeamOnPersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTeamOnPersonalAccount not implemented")
}
func (UnimplementedTeamServer) DeleteTeamFromPersonalAccount(context.Context, *DeleteTeamFromPersonalAccountRequest) (*DeleteTeamFromPersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeamFromPersonalAccount not implemented")
}
func (UnimplementedTeamServer) GetTeamsOnPersonalAccount(context.Context, *GetTeamsOnPersonalAccountRequest) (*GetTeamsOnPersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsOnPersonalAccount not implemented")
}
func (UnimplementedTeamServer) CheckTeamOnPersonalAccount(context.Context, *CheckTeamOnPersonalAccountRequest) (*CheckTeamOnPersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTeamOnPersonalAccount not implemented")
}
func (UnimplementedTeamServer) GetTeamBitrate(context.Context, *GetTeamBitrateRequest) (*GetTeamBitrateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamBitrate not implemented")
}
func (UnimplementedTeamServer) mustEmbedUnimplementedTeamServer() {}

// UnsafeTeamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeamServer will
// result in compilation errors.
type UnsafeTeamServer interface {
	mustEmbedUnimplementedTeamServer()
}

func RegisterTeamServer(s grpc.ServiceRegistrar, srv TeamServer) {
	s.RegisterService(&Team_ServiceDesc, srv)
}

func _Team_AddTeamOnPersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamOnPersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServer).AddTeamOnPersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Team/AddTeamOnPersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServer).AddTeamOnPersonalAccount(ctx, req.(*AddTeamOnPersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Team_DeleteTeamFromPersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamFromPersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServer).DeleteTeamFromPersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Team/DeleteTeamFromPersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServer).DeleteTeamFromPersonalAccount(ctx, req.(*DeleteTeamFromPersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Team_GetTeamsOnPersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamsOnPersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServer).GetTeamsOnPersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Team/GetTeamsOnPersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServer).GetTeamsOnPersonalAccount(ctx, req.(*GetTeamsOnPersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Team_CheckTeamOnPersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTeamOnPersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServer).CheckTeamOnPersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Team/CheckTeamOnPersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServer).CheckTeamOnPersonalAccount(ctx, req.(*CheckTeamOnPersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Team_GetTeamBitrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamBitrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServer).GetTeamBitrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Team/GetTeamBitrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServer).GetTeamBitrate(ctx, req.(*GetTeamBitrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Team_ServiceDesc is the grpc.ServiceDesc for Team service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Team_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tada.api.billing.Team",
	HandlerType: (*TeamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTeamOnPersonalAccount",
			Handler:    _Team_AddTeamOnPersonalAccount_Handler,
		},
		{
			MethodName: "DeleteTeamFromPersonalAccount",
			Handler:    _Team_DeleteTeamFromPersonalAccount_Handler,
		},
		{
			MethodName: "GetTeamsOnPersonalAccount",
			Handler:    _Team_GetTeamsOnPersonalAccount_Handler,
		},
		{
			MethodName: "CheckTeamOnPersonalAccount",
			Handler:    _Team_CheckTeamOnPersonalAccount_Handler,
		},
		{
			MethodName: "GetTeamBitrate",
			Handler:    _Team_GetTeamBitrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tada/api/billing/team_service.proto",
}
