// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package billing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WorkplaceClient is the client API for Workplace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkplaceClient interface {
	AddWorkplacesOnPersonalAccount(ctx context.Context, in *AddWorkplacesOnPersonalAccountRequest, opts ...grpc.CallOption) (*AddWorkplacesOnPersonalAccountResponse, error)
	ActivateWorkplacesOnPersonalAccount(ctx context.Context, in *ActivateWorkplacesOnPersonalAccountRequest, opts ...grpc.CallOption) (*ActivateWorkplacesOnPersonalAccountResponse, error)
	DeleteWorkplacesFromPersonalAccount(ctx context.Context, in *DeleteWorkplacesFromPersonalAccountRequest, opts ...grpc.CallOption) (*DeleteWorkplacesFromPersonalAccountResponse, error)
	AddUserInWorkplace(ctx context.Context, in *AddUserInWorkplaceRequest, opts ...grpc.CallOption) (*AddUserInWorkplaceResponse, error)
	DeleteUserFromWorkplace(ctx context.Context, in *DeleteUserFromWorkplaceRequest, opts ...grpc.CallOption) (*DeleteUserFromWorkplaceResponse, error)
	GetWorkplacesByPersonalAccount(ctx context.Context, in *GetWorkplacesByPersonalAccountRequest, opts ...grpc.CallOption) (*GetWorkplacesByPersonalAccountResponse, error)
	GetCountOfUnpaidWorkplacesByPersonalAccount(ctx context.Context, in *GetCountOfUnpaidWorkplacesByPersonalAccountRequest, opts ...grpc.CallOption) (*GetCountOfUnpaidWorkplacesByPersonalAccountResponse, error)
}

type workplaceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkplaceClient(cc grpc.ClientConnInterface) WorkplaceClient {
	return &workplaceClient{cc}
}

func (c *workplaceClient) AddWorkplacesOnPersonalAccount(ctx context.Context, in *AddWorkplacesOnPersonalAccountRequest, opts ...grpc.CallOption) (*AddWorkplacesOnPersonalAccountResponse, error) {
	out := new(AddWorkplacesOnPersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Workplace/AddWorkplacesOnPersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workplaceClient) ActivateWorkplacesOnPersonalAccount(ctx context.Context, in *ActivateWorkplacesOnPersonalAccountRequest, opts ...grpc.CallOption) (*ActivateWorkplacesOnPersonalAccountResponse, error) {
	out := new(ActivateWorkplacesOnPersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Workplace/ActivateWorkplacesOnPersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workplaceClient) DeleteWorkplacesFromPersonalAccount(ctx context.Context, in *DeleteWorkplacesFromPersonalAccountRequest, opts ...grpc.CallOption) (*DeleteWorkplacesFromPersonalAccountResponse, error) {
	out := new(DeleteWorkplacesFromPersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Workplace/DeleteWorkplacesFromPersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workplaceClient) AddUserInWorkplace(ctx context.Context, in *AddUserInWorkplaceRequest, opts ...grpc.CallOption) (*AddUserInWorkplaceResponse, error) {
	out := new(AddUserInWorkplaceResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Workplace/AddUserInWorkplace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workplaceClient) DeleteUserFromWorkplace(ctx context.Context, in *DeleteUserFromWorkplaceRequest, opts ...grpc.CallOption) (*DeleteUserFromWorkplaceResponse, error) {
	out := new(DeleteUserFromWorkplaceResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Workplace/DeleteUserFromWorkplace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workplaceClient) GetWorkplacesByPersonalAccount(ctx context.Context, in *GetWorkplacesByPersonalAccountRequest, opts ...grpc.CallOption) (*GetWorkplacesByPersonalAccountResponse, error) {
	out := new(GetWorkplacesByPersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Workplace/GetWorkplacesByPersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workplaceClient) GetCountOfUnpaidWorkplacesByPersonalAccount(ctx context.Context, in *GetCountOfUnpaidWorkplacesByPersonalAccountRequest, opts ...grpc.CallOption) (*GetCountOfUnpaidWorkplacesByPersonalAccountResponse, error) {
	out := new(GetCountOfUnpaidWorkplacesByPersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/tada.api.billing.Workplace/GetCountOfUnpaidWorkplacesByPersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkplaceServer is the server API for Workplace service.
// All implementations must embed UnimplementedWorkplaceServer
// for forward compatibility
type WorkplaceServer interface {
	AddWorkplacesOnPersonalAccount(context.Context, *AddWorkplacesOnPersonalAccountRequest) (*AddWorkplacesOnPersonalAccountResponse, error)
	ActivateWorkplacesOnPersonalAccount(context.Context, *ActivateWorkplacesOnPersonalAccountRequest) (*ActivateWorkplacesOnPersonalAccountResponse, error)
	DeleteWorkplacesFromPersonalAccount(context.Context, *DeleteWorkplacesFromPersonalAccountRequest) (*DeleteWorkplacesFromPersonalAccountResponse, error)
	AddUserInWorkplace(context.Context, *AddUserInWorkplaceRequest) (*AddUserInWorkplaceResponse, error)
	DeleteUserFromWorkplace(context.Context, *DeleteUserFromWorkplaceRequest) (*DeleteUserFromWorkplaceResponse, error)
	GetWorkplacesByPersonalAccount(context.Context, *GetWorkplacesByPersonalAccountRequest) (*GetWorkplacesByPersonalAccountResponse, error)
	GetCountOfUnpaidWorkplacesByPersonalAccount(context.Context, *GetCountOfUnpaidWorkplacesByPersonalAccountRequest) (*GetCountOfUnpaidWorkplacesByPersonalAccountResponse, error)
	mustEmbedUnimplementedWorkplaceServer()
}

// UnimplementedWorkplaceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkplaceServer struct {
}

func (UnimplementedWorkplaceServer) AddWorkplacesOnPersonalAccount(context.Context, *AddWorkplacesOnPersonalAccountRequest) (*AddWorkplacesOnPersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWorkplacesOnPersonalAccount not implemented")
}
func (UnimplementedWorkplaceServer) ActivateWorkplacesOnPersonalAccount(context.Context, *ActivateWorkplacesOnPersonalAccountRequest) (*ActivateWorkplacesOnPersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateWorkplacesOnPersonalAccount not implemented")
}
func (UnimplementedWorkplaceServer) DeleteWorkplacesFromPersonalAccount(context.Context, *DeleteWorkplacesFromPersonalAccountRequest) (*DeleteWorkplacesFromPersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkplacesFromPersonalAccount not implemented")
}
func (UnimplementedWorkplaceServer) AddUserInWorkplace(context.Context, *AddUserInWorkplaceRequest) (*AddUserInWorkplaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserInWorkplace not implemented")
}
func (UnimplementedWorkplaceServer) DeleteUserFromWorkplace(context.Context, *DeleteUserFromWorkplaceRequest) (*DeleteUserFromWorkplaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserFromWorkplace not implemented")
}
func (UnimplementedWorkplaceServer) GetWorkplacesByPersonalAccount(context.Context, *GetWorkplacesByPersonalAccountRequest) (*GetWorkplacesByPersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkplacesByPersonalAccount not implemented")
}
func (UnimplementedWorkplaceServer) GetCountOfUnpaidWorkplacesByPersonalAccount(context.Context, *GetCountOfUnpaidWorkplacesByPersonalAccountRequest) (*GetCountOfUnpaidWorkplacesByPersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountOfUnpaidWorkplacesByPersonalAccount not implemented")
}
func (UnimplementedWorkplaceServer) mustEmbedUnimplementedWorkplaceServer() {}

// UnsafeWorkplaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkplaceServer will
// result in compilation errors.
type UnsafeWorkplaceServer interface {
	mustEmbedUnimplementedWorkplaceServer()
}

func RegisterWorkplaceServer(s grpc.ServiceRegistrar, srv WorkplaceServer) {
	s.RegisterService(&Workplace_ServiceDesc, srv)
}

func _Workplace_AddWorkplacesOnPersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWorkplacesOnPersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkplaceServer).AddWorkplacesOnPersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Workplace/AddWorkplacesOnPersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkplaceServer).AddWorkplacesOnPersonalAccount(ctx, req.(*AddWorkplacesOnPersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workplace_ActivateWorkplacesOnPersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateWorkplacesOnPersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkplaceServer).ActivateWorkplacesOnPersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Workplace/ActivateWorkplacesOnPersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkplaceServer).ActivateWorkplacesOnPersonalAccount(ctx, req.(*ActivateWorkplacesOnPersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workplace_DeleteWorkplacesFromPersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkplacesFromPersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkplaceServer).DeleteWorkplacesFromPersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Workplace/DeleteWorkplacesFromPersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkplaceServer).DeleteWorkplacesFromPersonalAccount(ctx, req.(*DeleteWorkplacesFromPersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workplace_AddUserInWorkplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserInWorkplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkplaceServer).AddUserInWorkplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Workplace/AddUserInWorkplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkplaceServer).AddUserInWorkplace(ctx, req.(*AddUserInWorkplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workplace_DeleteUserFromWorkplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserFromWorkplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkplaceServer).DeleteUserFromWorkplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Workplace/DeleteUserFromWorkplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkplaceServer).DeleteUserFromWorkplace(ctx, req.(*DeleteUserFromWorkplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workplace_GetWorkplacesByPersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkplacesByPersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkplaceServer).GetWorkplacesByPersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Workplace/GetWorkplacesByPersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkplaceServer).GetWorkplacesByPersonalAccount(ctx, req.(*GetWorkplacesByPersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workplace_GetCountOfUnpaidWorkplacesByPersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountOfUnpaidWorkplacesByPersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkplaceServer).GetCountOfUnpaidWorkplacesByPersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tada.api.billing.Workplace/GetCountOfUnpaidWorkplacesByPersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkplaceServer).GetCountOfUnpaidWorkplacesByPersonalAccount(ctx, req.(*GetCountOfUnpaidWorkplacesByPersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Workplace_ServiceDesc is the grpc.ServiceDesc for Workplace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Workplace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tada.api.billing.Workplace",
	HandlerType: (*WorkplaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWorkplacesOnPersonalAccount",
			Handler:    _Workplace_AddWorkplacesOnPersonalAccount_Handler,
		},
		{
			MethodName: "ActivateWorkplacesOnPersonalAccount",
			Handler:    _Workplace_ActivateWorkplacesOnPersonalAccount_Handler,
		},
		{
			MethodName: "DeleteWorkplacesFromPersonalAccount",
			Handler:    _Workplace_DeleteWorkplacesFromPersonalAccount_Handler,
		},
		{
			MethodName: "AddUserInWorkplace",
			Handler:    _Workplace_AddUserInWorkplace_Handler,
		},
		{
			MethodName: "DeleteUserFromWorkplace",
			Handler:    _Workplace_DeleteUserFromWorkplace_Handler,
		},
		{
			MethodName: "GetWorkplacesByPersonalAccount",
			Handler:    _Workplace_GetWorkplacesByPersonalAccount_Handler,
		},
		{
			MethodName: "GetCountOfUnpaidWorkplacesByPersonalAccount",
			Handler:    _Workplace_GetCountOfUnpaidWorkplacesByPersonalAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tada/api/billing/workplace_service.proto",
}
